// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.VATRates
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("country")]
        public string Country { get; set; }

        [JsonProperty("countryName")]
        public string CountryName { get; set; }

        [JsonProperty("currency")]
        public string Currency { get; set; }

        [JsonProperty("effectiveFrom")]
        public DateTimeOffset EffectiveFrom { get; set; }

        [JsonProperty("rates")]
        public Rates Rates { get; set; }

        [JsonProperty("exception")]
        public object Exception { get; set; }
    }

    public partial class Rates
    {
        [JsonProperty("standard")]
        public long Standard { get; set; }

        [JsonProperty("reduced")]
        public long Reduced { get; set; }

        [JsonProperty("reduced2")]
        public object Reduced2 { get; set; }

        [JsonProperty("superReduced")]
        public object SuperReduced { get; set; }

        [JsonProperty("parking")]
        public object Parking { get; set; }
    }
}
